# Generated by Django 5.0.3 on 2024-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='account',
            name='jmbg',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='JMBG'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
