# Generated by Django 5.0.3 on 2024-09-24 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_destination_alter_account_name_alter_account_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_travelers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
