# Generated by Django 5.0.3 on 2024-09-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_booking_destination_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.destination'),
        ),
    ]
