# Generated by Django 5.0.3 on 2024-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_destination_alter_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
