# Generated by Django 5.0.3 on 2024-09-24 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_destination_price_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_travel',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
