# Generated by Django 5.0.3 on 2024-09-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
